### ISSUE TITLE
Can this project be evaluated in windows?

### ISSUE THREAD

**Issue by kumarballapavan** [lizhangray/TGL-Net#2]

**Comment by RaebingZhong** [comment]
Of course it can, but you need to config the python packages for the evaluation environment, especially the tensorflow version. And the checkpoint of model is also available in the repo.

**Comment by kumarballapavan** [comment]
What is the exact tensorflow version to be used? I had tried with version 2+ and 1.15.0. By this I am getting the below error:

runfile('D:/Study/NIT Research/Dehazing Matlab Codes/python/2021/J TGL-Net-main/TGL-Net-main/run_bak.py', wdir='D:/Study/NIT Research/Dehazing Matlab Codes/python/2021/J TGL-Net-main/TGL-Net-main')
Traceback (most recent call last):

  File "D:\Study\NIT Research\Dehazing Matlab Codes\python\2021\J TGL-Net-main\TGL-Net-main\run_bak.py", line 26, in <module>
    config = tf.ConfigProto()

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

**Comment by RaebingZhong** [comment]
As is written in the Requirement in readme, the version of tensorflow is required to be 1.14.0. I've seen that you have tried the version of  1.15.0. However, unfortunately, the APIs of tensorflow changed a lot during the updates between tensorflow 1.xx.xx. It would be good for you to right install the tensorflow of version 1.14.x.

**Comment by kumarballapavan** [comment]
I have reinstalled tensorflow version 1.14.0, now it is working well. But I need to reassign the variables with my path as follows:

checkpoint_dir='D:/Study/NIT Research/Dehazing Matlab Codes/python/2021/J TGL-Net-main/TGL-Net-main/model'
test_path ='D:/Study/NIT Research/Dehazing Matlab Codes/python/2021/J TGL-Net-main/TGL-Net-main/testset/4.png'
output_path='D:/Study/NIT Research/Dehazing Matlab Codes/python/2021/J TGL-Net-main/TGL-Net-main/result/'

Also, the program does not run continuously for the second time, I need to close the spyder and rerun the code with different image name. Anyways, thanks for sharing the code.

**Comment by RaebingZhong** [comment]
Thank you for your interest in our work. It would be very kind of you if you could close this issue, since we may have solved your problems? For any further problems, you are welcomed to reopen it or just open a new issue.
